      - name: Build WDA
        run: |
          cd WebDriverAgent
          mkdir -p build
          xcodebuild build-for-testing \
            -scheme WebDriverAgentRunner \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO
